vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_picture:
            uri_prefix: /images/user/avatar
            upload_destination: '%kernel.project_dir%/public/images/user/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
